### PR TITLE
feat: Add supported integrations and description

### PR DESCRIPTION
**Pull request by stjohnjohnson**
Added a list of supported integrations (kubernetes, swarm, etc) as well as a description.

screen shot 2016-12-13 at 23 39 12

Related epic: https://github.com/screwdriver-cd/screwdriver/issues/322

### CODE REVIEW

**Comment by tkyi** [comment]
Should we move the Getting Started to the bottom (like Concourse.ci's) and possibly move the team information into another page?
People are probably looking for more information about the product itself at the beginning to determine if they even want to use it or not, right?

**Comment by stjohnjohnson** [comment]
I'm torn.  I think most of the page should be information about the product with a clear call to action.  But I don't want to make another page just for team stuff.

**Comment by stjohnjohnson** [comment]
Also, I figure the getting started is going to move further and further down as we add more things.

**Comment by tkyi** [comment]
Okay well I think Features/Tech We Support should take precedence over Getting Started

**Comment by d2lam** [comment]
Agree with Tiff. I think most people would want to know what is supported before they even care to get started. 
The rest looks good 👍

**Comment by stjohnjohnson** [comment]
Updated

**Pull request merged**
